### ISSUE TITLE
TypeError: Cannot read property 'browserName' of undefined

### ISSUE THREAD

**Issue by richtmat** [wix/protractor-helpers#34]
While loading up the specs I can this error:

```
Spec started
Started

/home/matthias/development/repos/finderbox/finderbox-web-client/node_modules/protractor-helpers/dist/protractor-helpers.js:47
		this.browserName = cap.caps_.browserName;
                              ^
TypeError: Cannot read property 'browserName' of undefined
    at Helpers.<anonymous> (/home/matthias/development/repos/finderbox/finderbox-web-client/node_modules/protractor-helpers/dist/protractor-helpers.js:47:31)
    at Promise.invokeCallback_ (/home/matthias/development/repos/finderbox/finderbox-web-client/node_modules/selenium-webdriver/lib/promise.js:1329:14)
```

I'm using these versions:

protractor-helpers
grunt-protractor-runner: 3.1.0
protractor: 3.2.2

Removing the caps_ attribute from cap in line 47 solves the problem.

**Comment by richtmat** [comment]
I looked a bit further.

Running with protractor 3.0.0: all tests pass.
Running with protractor 3.1.0: not all tests pass.
Running with protractor 3.1.1: not all tests pass.
Running with protractor 3.2.0: tests won't even start.
Running with protractor 3.2.1: the error I described appears.

Hope that helps

**Comment by Freak613** [comment]
+1

**Comment by Nr9** [comment]
+1

**Comment by kuiqiang** [comment]
https://github.com/angular/protractor/issues/3036

**Comment by richtmat** [comment]
I'm added that in my fork: https://github.com/richtmat/protractor-helpers

**Comment by aravindkrish148** [comment]
Use processed cofig instead https://github.com/IgorSasovets/get-config-capabilities/blob/master/config.js

onPrepare: function() {
    return browser.getProcessedConfig().then(data => {
      global.deviceName = data.capabilities.browserName;
    });
  }
  
  you can call "global.deviceName" anywhere to get you browsername
